-- CREATE
--
--
--
CREATE DATABASE BIBLIOTECA_RONALDO;

USE BIBLIOTECA_RONALDO;

-- TABELA DE AUTORES
CREATE TABLE AUTORES(
	ID_AUTOR INT PRIMARY KEY,
	NOME_AUTOR VARCHAR (100) NOT NULL,
	DATA_NASCIMENTO_AUTOR CHAR (8)
);

-- TABELA DE LIVROS
CREATE TABLE LIVROS(
	ID_LIVRO INT PRIMARY KEY,
	TITULO VARCHAR(200),
	ID_AUTOR INT NOT NULL REFERENCES AUTORES (ID_AUTOR)
);

-- TABELA DE EMPRESTIMOS
CREATE TABLE EMPRESTIMOS(
	ID_EMPRESTIMO INT PRIMARY KEY,
	ID_LIVRO INT NOT NULL REFERENCES LIVROS (ID_LIVRO),
	DATA_EMPRESTIMO CHAR(8),
	DATA_DEVOLUCAO CHAR (8)
);