-- DELETE
--
--
--
-- BEGIN TRANSACTION

-- CONSTRUIR O COMANDO PARA PARA DELETAR ALGUM REGISTRO NA TABELA EMPRESTIMOS
DELETE FROM EMPRESTIMOS
WHERE ID_EMPRESTIMO = 555;

SELECT * FROM EMPRESTIMOS;

-- CONSTRUIR O COMANDO PARA PARA DELETAR ALGUM REGISTRO NA TABELA LIVROS
DELETE FROM LIVROS
WHERE ID_LIVRO = 984;

SELECT * FROM LIVROS;

/*CONSTRUIR O COMANDO PARA PARA DELETAR ALGUM REGISTRO NA TABELA AUTORES*/
DELETE FROM AUTORES
WHERE ID_AUTOR = 302;

SELECT * FROM AUTORES;

-- ROLLBACK