-- UPDATE
--
--
--
-- ALTERAR O NOME DE UM AUTOR NA TABELA AUTORES
-- BEGIN TRANSACTION

UPDATE AUTORES
SET NOME_AUTOR = 'Filipe Sabino'
WHERE ID_AUTOR = 302;

-- ROLLBACK TRANSACTION

SELECT * FROM AUTORES;

-- ALTERAR O TITULO DE ALGUM LIVRO NA TABELA LIVROS
-- BEGIN TRANSACTION

UPDATE LIVROS
SET TITULO = 'ELOGICA'
WHERE ID_LIVRO = 984;

-- ROLLBACK

SELECT * FROM LIVROS;

-- MARCAR UM LIVRO COMO EMPRESTADO E ATUALIZAR A DATA DE EMPRESTIMO E DATA DE DEVOLUCAO NA TABELA EMPRESTIMOS
-- BEGIN TRANSACTION

UPDATE EMPRESTIMOS
SET DATA_EMPRESTIMO = '20230807', DATA_DEVOLUCAO = NULL
WHERE ID_EMPRESTIMO = 111;

-- ROLLBACK

SELECT * FROM EMPRESTIMOS;